### ISSUE TITLE
Empty path after page refresh (hash router)

### ISSUE THREAD

**Issue by sheridanchris** [JordanMarr/Fable.LitRouter#1]
The path seems to be empty after a full page reload when using `RouteMode.Hash`.
This works as expected when using `RouteMode.Path`

![msedge_hnFvfOUK1C](https://user-images.githubusercontent.com/105478675/210188289-9cfb9cd0-23c7-4201-aa24-9465f43e8f39.gif)

repro:
```fsharp
[<LitElement("my-app")>]
let MyApp () =
  let _ = LitElement.init (fun cfg -> cfg.useShadowDom <- false)
  let route = Hook.useRouter RouteMode.Hash

  html
    $"""
    <p>Hello, World!</p>
    {match route with
     | [] -> html $"<h1>Home</h1>"
     | [ "test" ] -> html $"<h1>Test</h1>"
     | _ -> html $"<h1>Not found</h1>"}
    """
```

**Comment by JordanMarr** [comment]
This should now be fixed in v1.0.0.
