### ISSUE TITLE
"useRouter" hook not triggered when using browser's back button

### ISSUE THREAD

**Issue by dneivzz** [JordanMarr/Fable.LitRouter#2]
Hi,

It looks like when I enter a path in the address bar to load a page in the app, then programmatically navigate from that page to another (dispatching `Cmd.navigatePath` in `update` function or calling `Router.navigatePath()`), and then try to go back to the previous page using the browser's back button, the App component with the useRouter hook does not get rerendered, which means the app stays on the 2nd page.

### Steps to reproduce:

1. Enter url to load the 1st page (in this case: `http://domain/recipe-search`)
2. Dispatch `LitRouter.Cmd.navigatePath $"""/recipe-search-result?ingredients={model.SelectedIngredients
                                             |> Set.toSeq
                                             |> String.concat ","}"""` from 1st page to load 2nd page
3. From 2nd page, click on browser's back button

### Expected behavior
The main App component gets re-rendered (triggered by the useRouter hook) and the 1st page in shown

### Actual behavior
The App component does not get re-rendered, browser's windo remains on 2nd page despite the address bar's url is back to that of 1st page

App.fs component (recipe-search is 1st page, recipe-search-result is 2nd page):

```fsharp
[<LitElement("my-app")>]
let MyApp () =
  let _ =
    LitElement.init (fun cfg -> cfg.useShadowDom <- false)

  let ctx = Hook.useStore (AppContext.store)
  let path = Hook.useRouter (RouteMode.Path)
 //...
  html
    $"""
 //...
        {
        <main style="max-width: 640px;margin: 0 auto;">
            {match path with
             | [] -> Home.Page()
             | "recipe-search" :: _ -> RecipeSearch.Page()
             | "recipe-search-result" :: _ -> RecipeSearchResult.Page()
             | "callback" :: _ -> html $"<h1>Loading...</h1>"
             | _ -> html $"<h1>Page not found.</h1>"}
        </main>
```

RecipeSearch's update function:
```fsharp
let update msg model =
  | SearchRecipes ->
    model,
    LitRouter.Cmd.navigatePath
      $"""/recipe-search-result?ingredients={model.SelectedIngredients
                                             |> Set.toSeq
                                             |> String.concat ","}"""
```

### Extra Information
I tried debugging the LitRouter, it looks like this function got called:
```fsharp
let onChange (e: Event) = 
                Router.onUrlChange routeMode setPath e
```
But unlike programmatic navigation, App component doesn't get re-rendered when the browser's back button is clicked.

**Comment by JordanMarr** [comment]
I am unable to reproduce your issue. I've tried using both `Router.navigatePath` and `Cmd.navigatePath`, and I am able to use the browser back successfully in both cases.

A few questions:
* Which version of Fable.LitRouter are you using? (The latest is v1.0.0 which was released a few days ago).
* Are you using `RouteMode.Path` or `RouteMode.Hash`?

**Comment by dneivzz** [comment]
I've figured out the issue!

In my 2nd page Hook component, I called `Hook.useRouter` to get the current path:
```fsharp
let path = Hook.useRouter (RouteMode.Path)
```

After comparing the routing behavior with your fable-lit-fullstack-template app (which works), I realized this is improper use of this library.

Fixed this line to the following and I got the expected behavior:
```fsharp
let path = Hook.currentPath ()
```

**Comment by JordanMarr** [comment]
Glad you got it resolved. 😎
